"""fix self-referential relationship remote_side

Revision ID: 66033398f0f3
Revises: ccd7fcfa9531
Create Date: 2026-09-28 18:55:04.890429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66033398f0f3'
down_revision: Union[str, None] = 'ccd7fcfa9531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###