"""create auth tables: users, tutor_profiles, tutor_applications

Revision ID: c026c51f781d
Revises: 002
Create Date: 2026-09-28 14:29:52.021030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c026c51f781d'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TUTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('native_language', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tutor_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'DOCUMENTS_REVIEW', 'ENGLISH_TEST', 'DEMO_LESSON', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_verification_provider', sa.String(length=50), nullable=True),
    sa.Column('id_verification_id', sa.String(length=100), nullable=True),
    sa.Column('id_verification_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='verificationstatus'), nullable=False),
    sa.Column('qualification_type', sa.String(length=50), nullable=True),
    sa.Column('qualification_file_url', sa.String(length=500), nullable=True),
    sa.Column('qualification_verified', sa.Boolean(), nullable=False),
    sa.Column('english_proof_type', sa.String(length=50), nullable=True),
    sa.Column('english_score', sa.String(length=50), nullable=True),
    sa.Column('english_verified', sa.Boolean(), nullable=False),
    sa.Column('intro_video_url', sa.String(length=500), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('specialties', sa.Text(), nullable=False),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('availability_json', sa.Text(), nullable=True),
    sa.Column('tech_confirmed', sa.Boolean(), nullable=False),
    sa.Column('code_of_conduct_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_agreement_accepted', sa.Boolean(), nullable=False),
    sa.Column('recording_consent', sa.Boolean(), nullable=False),
    sa.Column('reference_1_name', sa.String(length=100), nullable=True),
    sa.Column('reference_1_email', sa.String(length=255), nullable=True),
    sa.Column('reference_2_name', sa.String(length=100), nullable=True),
    sa.Column('reference_2_email', sa.String(length=255), nullable=True),
    sa.Column('background_check_provider', sa.String(length=50), nullable=True),
    sa.Column('background_check_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='verificationstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('demo_lesson_score', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_tutor_applications_status', 'tutor_applications', ['status'], unique=False)
    op.create_table('tutor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('payout_details', sa.Text(), nullable=True),
    sa.Column('intro_video_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tutor_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tutor_availability_profile_day', 'tutor_availability', ['profile_id', 'day_of_week'], unique=False)
    op.create_table('tutor_profile_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_profile_specialties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_profile_specialties')
    op.drop_table('tutor_profile_languages')
    op.drop_index('ix_tutor_availability_profile_day', table_name='tutor_availability')
    op.drop_table('tutor_availability')
    op.drop_table('tutor_profiles')
    op.drop_index('ix_tutor_applications_status', table_name='tutor_applications')
    op.drop_table('tutor_applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###