"""add learner fields and classes table

Revision ID: ccd7fcfa9531
Revises: 7b8953a6874f
Create Date: 2026-09-28 18:53:29.409965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd7fcfa9531'
down_revision: Union[str, None] = '7b8953a6874f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tutor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('proficiency_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='proficiencylevel'), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['tutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'proficiency_level')
    op.drop_column('users', 'tutor_id')
    # ### end Alembic commands ###